services:
  musicncs:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: music-ncs-api
    restart: unless-stopped
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=production
      - PORT=3006
    volumes:
      - ./logs:/app/logs
    networks:
      - bellukstudio_network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
          cpus: "0.25"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3006/health"]           
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  bellukstudio_network:
    external: true      